aquarist-labs/s3gw-tools

- README.md
> readme: update a few things related to running radosgw

- k3s/.gitignore
- k3s/longhorn-pvc.yaml
- k3s/longhorn-storageclass.yaml
- k3s/s3gw-ingress.yaml
- k3s/s3gw-pod.yaml
- k3s/s3gw-service.yaml
- k3s/setup.sh
> k3s: Run k3s in rootless mode.

- k3s/setup.sh
> k3s: Make sure open-iscsi is installed

- k3s/setup.sh
- Search for local s3gw image and use it by default.
- Add '--s3gw-image' option to define a different s3gw image. Defaults to 'ghcr.io/aquarist-labs/s3gw:latest'.
New behaviour: Look for local s3gw image. If it exists, then import that into k3s, otherwise pull it from ghcr.io.
> Various improvements related to s3gw image

- docs/release-notes/s3gw-v0.1.0.md
> docs: release notes for v0.1.0

- .github/workflows/lint.yaml
- README.md
- docs/build-ui.md
- docs/build.md
- docs/contributing.md
- docs/decisions/.markdownlint.yml
- docs/decisions/0000-use-markdown-any-decision-records.md
- docs/decisions/README.md
- docs/decisions/adr-template.md
- docs/developing.md
- docs/env-k3s.md
- docs/env-k8s.md
- docs/release-notes/s3gw-v0.1.0.md
- docs/s3-compatibility-table.md
- docs/s3gw-repos.md
- docs/testing.md
Uses template from https://adr.github.io/madr/
> RFC: Use MADRs to records architecture, design and code decisions

- tests/s3gw-bench.sh
> test/bench: write results to specific directory

- build-ui/build.sh
- env/setup.sh
- Use same log format to STDOUT/STDERR
- Add commands to import local s3gw and s3gw-ui images to k3s
> Improve build/setup scripts

- env/setup.sh
This PR allows you to install k3s only to be able to test the installation of the [chart](https://github.com/aquarist-labs/s3gw-charts).
> Add '--no-s3gw' argument to install k3s (and iSCSI + Longhorn) only.

- env/setup.sh
Related to: https://github.com/aquarist-labs/s3gw/issues/31
> Display a hint how to workaround the HTTPS/CORS issue.

- env/setup.sh
> Call correct function.

- env/setup.sh
> If '--dev' is enabled, the s3gw-ui image is not imported.

- env/setup.sh
> Display all existing URLs.

- env/setup.sh
> Fix setup script (call correct function).

- env/setup.sh
- Display some more information which local image is exported.
- Modify info messages.
> Display more information.

- build-ui/Dockerfile.app
The change has been done with https://github.com/aquarist-labs/s3gw-ui/commit/c9e0ad521749cd0ab2813a1e9ed11823ecc1f5d2.
> Adapt name of sample/template file.

- tests/s3gw-test.sh
> tests: add helper to run scripts

- tests/s3gw-smoke-test.sh
Requires aquarist-labs/ceph#17 to be merged.
> test/smoke: add a few more smoke tests

- CHANGELOG.md
Updated changelog for 0.4.0 release
> Updated changelog for 0.4.0 release

- .github/pull_request_template.md
This PR implements a Pull Request template. It was proposed [in this PR](https://github.com/aquarist-labs/s3gw/pull/97).
https://github.com/aquarist-labs/s3gw/issues/22
Signed-off-by: Jesus HM <jherman@suse.com>
> Adds PR template to Tools repository

- tests/s3gw-versioning-smoke-tests.py
After this PR is merged https://github.com/aquarist-labs/ceph/pull/38 we need to update the versioning tests to reflect the delete markers.
> test/smoke: versioning tests with delete markers

- CHANGELOG.md
Updated CHANGELOG.md with 0.6.0 release label
> Updated CHANGELOG.md with 0.6.0 release label

- CHANGELOG.md
- build/Dockerfile.build-container
- build/Dockerfile.build-radosgw-test-container
Fixes: https://github.com/aquarist-labs/s3gw/issues/161
libfmt system package updated to version 9 in gateway's Dockerfiles
> libfmt system package updated to version 9 in gateway's Dockerfiles

- CHANGELOG.md
> Update release date for 0.7.0

- CHANGELOG.md
> Fix misplaced entry on CHANGELOG.md

- CHANGELOG.md
Signed-off-by: Volker Theile <vtheile@suse.com># Describe your changes
> Merge `v0.8.0` branch into `main`.

- CHANGELOG.md
- build/Dockerfile.build-radosgw-test-container
- build/build-radosgw.sh
- build/build.sh
Adds 2 new unit tests added to rgw after merging the following PRs: 
https://github.com/aquarist-labs/ceph/pull/59
https://github.com/aquarist-labs/ceph/pull/56
> tools: add new rgw/sfs unit tests

- CHANGELOG.md
Merge main with release branch v0.9.0
> Merge w v0.9.0

- .markdownlint.json
- .markdownlint.jsonc
- README.md
- Fix broken links in badges
- Add more informative description
- Remove duplicate config for markdownlint
- Change description to match the repos purpose as it is no longer the main repo of the project
> docs: fixup readme
