build/Dockerfile.build-container
build/README.md
build/build-container.sh

- User can now choose to build the s3gw container with docker also.
Regardless of what is employed - podman or docker engine - to build it, produced image will be OCI compliant. 
Fixes: aquarist-labs/s3gw#27

s3gw container for docker

---

build/Dockerfile.build-container
build/README.md
build/build-container.sh

User can override --rgw-backend-store and --debug-rgw arguments.
They default respectively with values: dbstore, 1.

default arguments for s3gw container

---

build/Dockerfile.build-radosgw

Currently, the build-radosgw container has a minimal set of packages necessary for the build, then later when you *run* the container, it calls out to `install-deps.sh` from the ceph source tree to install ceph's build dependencies (300+ rpms). This takes about 15 minutes (for me, at least, with my rural Tasmanian internet connection), and happens every time I run the build-radosgw container to build ceph.  If we put all these dependencies inside Dockerfile.build-radosgw instead, they only get downloaded once, when building that container.  We still run `install-deps.sh` in case any new dependencies have been added to ceph in the meantime, but at least we'll have almost all of them upfront.
~I've also added mirrorsorcerer which updates the zypper repos to whichever mirror is closest to …

Add rpms from install-deps.sh to Dockerfile.build-radosgw

---

build/Dockerfile.build-container
build/build-container.sh

- Use Dockerfile for podman and docker to reduce duplicate code.
- Add missing options in Dockerfile.

Cleanup build script.

---

build/build-radosgw.sh

This _massively_ speeds up builds (after the first one, at least).
Signed-off-by: Tim Serong <tserong@suse.com>

Persist CCACHE_DIR to host

---

k8s/README.md
k8s/Vagrantfile
k8s/ingresses/s3gw-ingress-no-tls.yaml
k8s/ingresses/s3gw-ingress.yaml
k8s/playbooks/bootstrap.yaml
k8s/playbooks/ingress-deploy.yaml
k8s/playbooks/k8s-install.yaml
k8s/playbooks/lh-deploy.yaml
k8s/playbooks/s3gw-deploy.yaml
k8s/s3gw/s3gw-deployment.yaml
k8s/s3gwctl

Various Improvements on k8s environment:
- k8s stable upgraded to 1.24.0 from 1.23.x line;
with this release Docker support has been removed.
Due to this, project playbooks have been updated in order
to configure containerd as CRI interface for k8s.
- Added some options when building the environment.
A notable option is that now you can choose the s3gw
image to use in the deployment.
- Added start command in s3gwctl
- Added no-tls ingress for s3gw
- Added the ability to choose if allocate a disk for admin/worker on cluster
- Set client_max_body_size to 0 for s3gw's ingress
- Some cleaning

k8s environment improvements

---

README.md
build/Dockerfile.build-radosgw
build/build-radosgw.sh
env/setup_k3s.sh

Stripping the binary and shared libraries will reduce the size of the container image about 20MiB.
References:
- https://github.com/Debian/debhelper/blob/master/dh_strip
- https://www.thegeekstuff.com/2012/09/strip-command-examples/
Fixes: https://github.com/aquarist-labs/s3gw-core/issues/54

Strip unnecessary data from radosgw binary.

---

.gitignore
tests/.gitignore
tests/README.md
tests/create-s3tests-report.sh
tests/s3gw-bench.sh
tests/s3gw-s3tests.sh
tests/s3gw-smoke-test.sh

These are to be run against a file based backend. As they stand, the access key and secret key are not configurable to support dbstore and the likes.
This is meant as something to be expanded on, instead of implementing a comprehensive solution right now.

s3gw/tests: add rudimentary smoke tests and benchmark

---

tests/create-s3tests-report.sh

After changing where we keep the s3tests reports in the s3gw-status
repository, there was a little path that was not properly changed.

tests/s3tests: fix report publishing

---

build/Dockerfile.build-radosgw
build/build-radosgw.sh

- Use system boost to build against.
This reduces the compile time a bit.
- Configure git safe directory in the build container.
Since git v2.35.2, this is necessary e.g. for `git submodule update`

build: use system boost

---

build/Dockerfile.build-container

- Install system boost libraries in the s3gw container
- Copy shared object files explicitly
Since we are building against system boost libraries, this is necessary
to run the radosgw binary.
Copying shared object files explicitly avoids accidentally copying
additional files, thereby increasing image size unnecessarily.

radosgw-container: install system boost libraries

---

build/Dockerfile.build-radosgw

After merging [this PR](https://github.com/aquarist-labs/ceph/pull/12) the simplefile store in radosgw needs `libsqliteorm` when building.
This adds the OBS repository containing libsqliteorm and installs it.
Nothing else is needed, as `sqlite_orm` is a header only library.

Install libsqliteorm from OBS repository.

---

tests/create-s3tests-report.sh

Add option to specify name of test report in the report generation
script.
This will be useful, when using the script in a CI pipeline, because
it simplifies handling of the resulting report file.

tests: add option for named test report

---

tests/awsauth.py
tests/s3gw-users-rest-api-test.py

This is related to PR: https://github.com/aquarist-labs/ceph/pull/15
Adds some very basic tests to detect regressions for sfs's user rest api.
It also adds the `awsauth.py` file from ceph's source code, I'm not 100% convinced we should do this, so open for discussion.

Add simple smoke tests for sfs user management via rest api

---

docs/testing.md

Added documentation in docs/testing.md for building a stress test scenario with fio against s3gw.
If you have other ideas or desiderata you would like to implement, please elaborate.
Fixes: https://github.com/aquarist-labs/s3gw-core/issues/93

Stress testing s3gw with fio

---

env/s3cmd.cfg

I need this for the blog post.
- Updated s3cmd.cfg to reflect the default access_key/secret_key values
used by s3gw

Updated s3cmd config file

---

env/s3cmd.cfg

See [env/s3gw/s3gw-secret.yaml](https://github.com/aquarist-labs/s3gw-tools/blob/main/env/s3gw/s3gw-secret.yaml) file.

Adapt the access/secret key in s3cmd.cfg to the values that are deployed by the scripts.

---

.github/workflows/build-environment.yaml

Make the build-environment callable. This will be used to create tagged
container images when the aquarist-labs/s3gw repo is tagged and a
project release is triggered.
The aim is that the container tagged with :latest contains the latest
changes in this repo. But there are also containers tagged with the
project's release version containing the correct contents for that
specific release.

ci: make build-environment workflow callable

---

tests/s3gw-users-rest-api-test.py

tests: Add unit test for the '/admin/metadata/user' AdminOps API endpoint.

---

.github/workflows/build-environment.yaml

Use credentials provided by caller when the workflow is called from a different repo. This is needed for when the workflow is called from the s3gw repo since secrets are not accessible in called workflows.

ci: use credentials provided by caller

---

tests/s3gw-versioning-smoke-tests.py

Adds a few versioning tests for verifying objects versions.
It also adds a few non versioned tests for checking that non-versioned
buckets work as expected.
Note: it requires boto3 python module.

test/smoke: add versioning tests

---

tests/s3gw-smoke-test.sh

After PR https://github.com/aquarist-labs/ceph/pull/43 is merged we are able now to delete the bucket in the smoke test.

test/smoke: Delete bucket in smoke test

---

CHANGELOG.md
build/Dockerfile.build-radosgw-test-container
build/build-radosgw-test-container.sh
build/build-radosgw.sh
build/build.sh

Note: this PR alone is not sufficient to cover the [issue](https://github.com/aquarist-labs/s3gw/issues/94)'s functional requisite.
Other PR(s) will be opened on the relevant repos.
Added the ability to build a s3gw-test image able to run google-tests related to radosgw sfs backend development.
example steps:
```
./build.sh build-image
S3GW_CEPH_DIR=../../ceph S3GW_CCACHE_DIR=../../ceph/build.ccache.s3gw WITH_TESTS=ON ./build.sh radosgw
S3GW_CEPH_DIR=../../ceph ./build.sh s3gw-test
podman run localhost/s3gw-test
```
https://github.com/aquarist-labs/s3gw/issues/94

build/s3gw-test: s3gw-test image

---

build/build-radosgw.sh

Assuming at least git 2.36 is used, this fixes the git safe.directory debacle when building as different user (e.g. root in a container ) than the one owning the git repo's directory.

build: fix git safe dir

---

CHANGELOG.md
build/Dockerfile.build-container
build/Dockerfile.build-radosgw-test-container

This patch is needed as prerequisite for: https://github.com/aquarist-labs/s3gw/issues/164

build: radosgw binaries have been moved to /radosgw directory in gateway's Dockerfiles

---

CHANGELOG.md
scripts/patch-s3gw-deployment.sh

This PR depends on https://github.com/aquarist-labs/s3gw-tools/pull/180
`script/patch-s3gw-deployment.sh
`
This script should be used while doing development on s3gw's radosgw binaries.
By calling this script, we patch the s3gw deployment inside k8s as this:
1) A base image is used, ghcr.io/aquarist-labs/s3gw:latest (default).
2) We create a PVC and a helper copier pod that mounts that PVC.
3) We copy the built binaries on the PVC by calling an equivalent `kubectl cp` command
on the copier pod.
4) We mount the same PVC on the s3gw pod at the location where
the binaries are expected (/radosgw).
Patching the deployment forces the s3gw pod to restart with the new binaries in place.
Fixes: https://github.com/aquarist-labs/s3gw/issues/164
Signed-off-by: Giuseppe Baccini …

Added a script able to update the s3gw's deployment in Kubernetes

---

build/Dockerfile.build-radosgw-test-container

There was an error introduced in PR: https://github.com/aquarist-labs/s3gw-tools/pull/192
This removes the extra quotes added in the Dockerfile

tools: Fix test container Dockerfile
